name: Docker Image CI
on: [push, pull_request]
jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go: [1]
        flag: [1]

    steps:
    - uses: actions/checkout@v3
    - name: InstallGo
      uses: actions/setup-go@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
